name: Manual Documentation Sync

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      source_commit:
        description: 'Source commit hash (optional)'
        required: false
        default: 'main'

# Set permissions for the workflow
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout quantum-docs repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Checkout quantum-platform repository
      uses: actions/checkout@v4
      with:
        repository: Dylan-Natter/quantum-platform
        path: quantum-platform
        fetch-depth: 0
        ref: ${{ github.event.inputs.source_commit || 'main' }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Sync documentation
      run: |
        echo "🔄 Syncing documentation from quantum-platform..."
        
        # Create backup
        mkdir -p backup
        cp -r docs backup/docs-backup-$(date +%Y%m%d-%H%M%S) 2>/dev/null || echo "No existing docs to backup"
        
        # Sync docs
        rsync -av --delete \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='*.log' \
          quantum-platform/docs/ docs/
        
        echo "📋 Documentation sync completed"
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "✅ No changes detected"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "📝 Changes detected, proceeding with deployment"
        fi
    
    - name: Commit and push changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add docs/
        git commit -m "docs: manual sync from quantum-platform
        
        - Manual sync triggered from GitHub Actions
        - Source: quantum-platform@${{ github.event.inputs.source_commit || 'main' }}
        - Timestamp: $(date)
        - Workflow: ${{ github.workflow }}
        - Run ID: ${{ github.run_id }}"
        
        git push origin main
    
    - name: Setup Pages
      if: steps.changes.outputs.changed == 'true'
      uses: actions/configure-pages@v4
    
    - name: Build
      if: steps.changes.outputs.changed == 'true'
      run: npm run build
    
    - name: Upload artifact
      if: steps.changes.outputs.changed == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build
    
    - name: Deploy to GitHub Pages
      if: steps.changes.outputs.changed == 'true'
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Notify completion
      if: always()
      run: |
        if [ "${{ steps.changes.outputs.changed }}" == "true" ]; then
          echo "✅ Documentation successfully synced and deployed!"
          echo "🌐 Site updated at: https://docs.quantum.centrex.ai"
        else
          echo "ℹ️  No changes to sync"
        fi
